# Generated by Django 2.1.7 on 2019-06-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190606_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='api_id',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='predicted_duration',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
