# Generated by Django 2.1.7 on 2019-06-06 00:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CremeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(unique=True)),
                ('pipeline', picklefield.fields.PickledObjectField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'models',
                'db_table': 't_creme_models',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_id', models.PositiveIntegerField()),
                ('rq_job_id', models.UUIDField(null=True)),
                ('raw_info', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('started_at', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(null=True)),
                ('predicted_duration', models.PositiveIntegerField(null=True)),
                ('winning_team_id', models.PositiveSmallIntegerField(null=True)),
                ('predicted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CremeModel')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'db_table': 't_matches',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('short_name', models.TextField()),
                ('full_name', models.TextField()),
                ('platform', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'regions',
                'db_table': 't_regions',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Region'),
        ),
    ]
