# Generated by Django 2.1.7 on 2019-06-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='predicted_duration',
            field=models.IntegerField(null=True),
        ),
    ]
