# Generated by Django 2.1.7 on 2019-06-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190606_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='api_id',
            field=models.TextField(),
        ),
    ]
